osc: Depends on curl for Linuxbrew
Fix the error:
__main__.ConfigurationError: Could not run curl-config:
[Errno 2] No such file or directory

Closes Linuxbrew/homebrew-core#2751.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>