bioawk: Depends on bison [Linux]
Fix the errors:
make: yacc: Command not found
addon.c:241:77: fatal error: zlib.h: No such file or directory

Closes Linuxbrew/homebrew-core#5443.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>