python@3.8: Rebuild 3.8.2 bottle (#19821)
- We merged this from Homebrew/homebrew-core in
  8d71cfb13edd93bb1cd6fa860d6716c20814579e, but there weren't any
  conflicts in the bottle lines, so we didn't remove the old SHA, so the
  new version's bottle didn't build successfully.

```
==> brew bottle --merge --write --no-commit ./python@3.8--3.8.2.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
==> python@3.8
==> FAILED
```