gobby: Fix build for Linux (#19545)
* gobby: Fix build for Linux

From
https://github.com/Homebrew/linuxbrew-core/runs/434444958?check_suite_focus=true:

```
checking for perl >= 5.8.1... 5.22.1
checking for XML::Parser... configure: error: XML::Parser perl module is
required for intltool
```

* gobby: Skip test if on Linux CI

```
==> brew test gobby --verbose
Testing gobby
==> /home/linuxbrew/.linuxbrew/Cellar/gobby/0.5.0_7/bin/gobby-0.5
--version
Cannot open display:
Error: gobby: failed
```