analog: Fix [Linux]
* Link against -lm to fix error: undefined reference to `cos'
* Disable other macOS-specific Make rules
* Depend on zlib; it's not strictly necessary but clearly
  was intended to be used.

Signed-off-by: Bob W. Hogg <rwhogg@linux.com>

Closes Linuxbrew/homebrew-core#4030.

Signed-off-by: Michka Popoff <michkapopoff@gmail.com>