git: Depends on openssl and curl for Linuxbrew
Fix the error:
http.h:6:23: fatal error: curl/curl.h: No such file or directory

Closes Linuxbrew/homebrew-core#2647.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>