[Actions/formulae.brew.sh] Rebase on origin/master before pushing (#18297)
- When we push lots of commits at once (say, merging multiple bottle PRs) to master and the Action runs to update formulae.brew.sh, it fails on the later one [1] because it doesn't fetch and rebase against the latest master.
- This was also a problem in Homebrew/homebrew-core, so this copies their approach to solving it: `git fetch` and `git rebase origin/master`.

```
[1]
error: failed to push some refs to 'git@github.com:Homebrew/formulae.brew.sh'
hint: Updates were rejected because the remote contains work that you do not have locally.
```