Revert "mongo-c-driver: update 1.6.3 bottle for Linuxbrew."
This reverts commit a90b5c1176ce05c3ea50743b6eb269e0828a7ab5.

Fix the errors:
/home/linuxbrew/.linuxbrew/Cellar/mongo-cxx-driver/3.1.2/lib/libmongocxx.so:
undefined reference to `mongoc_client_set_ssl_opts'
undefined reference to `mongoc_client_pool_set_ssl_opts'
collect2: error: ld returned 1 exit status