appscale-tools: Fix CI build by specifying pkg-config dependency
- This branch _and_ the master branch was failing in CI (and a local
  Docker container) at the `` step with:

  ```
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
  compilation terminated.
  error: command 'gcc-5' failed with exit status 1
  ```
- Looking at other formulae that depend on libffi, they also have a
  dependency on `pkg-config`, and that was the missing element here too.