charm-tools: Depends on libffi for Linuxbrew
Fix the error:
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

Closes Linuxbrew/homebrew-core#2769.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>