libxml2: Depends on python for Linuxbrew
Fix the error:
libxml2-py.c:3:20: fatal error: Python.h: No such file or directory

Closes Linuxbrew/homebrew-core#2799.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>