aide: Depends on curl, bison, and flex for Linuxbrew
Also explicitly specify the Linuxbrew curl path.

Fix errors:

* AIDE requires GNU bison
* AIDE requires GNU flex
* configure: error: You don't have curl properly installed
* undefined reference to `curl_easy_init'

Closes Linuxbrew/homebrew-core#455.

Signed-off-by: Bob W. Hogg <rwhogg@linux.com>