itstool: Rebuild the bottle [Linux]
Fix the test error:
ImportError: dynamic module does not define module export function (PyInit_libxml2mod)

Closes Linuxbrew/homebrew-core#9051.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>