buku: update 3.1 bottle and fixes for Linuxbrew
On Linux, we need a few extra packages:
 * libffi
 * pkg-config (needed to find libffi)
 * expect

We also need to set 'PYTHONIOENCODING' env. var. to 'utf-8' because
otherwise, 'buku' displays an error:

```
  File "/home/linuxbrew/.linuxbrew/bin/buku", line 1827, in program_info
    ''' % (__version__, __author__, __license__))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 131: ordinal not in range(128)
```

We also have to un-hard-code '/usr/bin/expect' and change that to
"#{Formula["expect"].opt_bin}/expect"

Closes Linuxbrew/homebrew-core#3281.
Signed-off-by: Maxim Belkin <maxim.belkin@gmail.com>