docker-compose: Fix build for Linux
- Error:
  ```
  gcc-5 -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/linuxbrew/.linuxbrew/opt/python/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
  ```
- I've added the `libffi` dependency and specified its location.
- Gist logs: none, 'cause this was only reproducible in Docker for me,
  but see the error in issue 14131 or in the failed bottle PR 14028.

Closes #14253.

Signed-off-by: Michka Popoff <michkapopoff@gmail>