clib: Depends on curl [Linux]
Says it's a runtime dependency on the website;
also fails on Circle.

Fix error:
undefined reference to `curl_easy_init'

Signed-off-by: Bob W. Hogg <rwhogg@linux.com>

Closes Linuxbrew/homebrew-core#3965.

Signed-off-by: Michka Popoff <michkapopoff@gmail.com>