freeglut: Depends on mesa and glu for Linuxbrew
Fix the errors:
Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
error: GL/glu.h: No such file or directory

Closes Linuxbrew/homebrew-core#1772.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>