w3m: Depends on homebrew/dupes/ncurses for Linuxbrew
Fix error:
terms.c:(.text+0x2bf): undefined reference to `tgetnum'

Closes Linuxbrew/homebrew-core#924.

Signed-off-by: Bob W. Hogg <rwhogg@linux.com>