boost-python: Depends on python for Linuxbrew
Fix the errors:

/usr/bin/ld: cannot find -lpython2.7

ImportError: /home/linuxbrew/.linuxbrew/lib/libboost_python.so.1.64.0:
undefined symbol: PyUnicodeUCS4_FromEncodedObject

Closes Linuxbrew/homebrew-core#2794.

Signed-off-by: Shaun Jackman <sjackman@gmail.com>