Revert "charm-tools: update 2.2.0 bottle for Linuxbrew."
This reverts commit 8e4fd6a6f27c1d19911ec7548e724929802f5e6a.

This bottle does not work.
$ charm-version
Traceback (most recent call last):
  File "/home/sjackman/.linuxbrew/bin/charm-version", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/sjackman/.linuxbrew/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__