Revert "easyrpg-player: update 0.5.1_1 bottle for Linuxbrew."
This reverts commit 24daf351208551bf98df13721abb250cb0a83142.

Fix the error:
==> /home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player -v
/home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/liblcf.so.0)
/home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linuxbrew/.linuxbrew/lib/liblcf.so.0)
/home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/liblcf.so.0)
Error: easyrpg-player: failed
<0> expected but was
<1>.
==> FAILED